stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t my-backend-image .

test-job:
  stage: test
  script:
    - docker run --rm my-backend-image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose up -d