name: Deploy Project

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Build, tag, and push image
      id: build-image
      run:
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker compose up -d
